language: csharp
solution: NullFX.CRC.sln
install:
  - nuget restore NullFX.CRC.sln
script:
  - xbuild /p:Configuration=Release solution-name.sln
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
